### ISSUE TITLE
Issues with sizes : Error_WrongBufferSize

### ISSUE THREAD

**Issue by igniuss** [SlightlyMad/AsyncTextureReader#1]
So, I'm trying to use this for retrieving an RWStructuredBuffer of a custom struct, containing 2 Vector4s
`struct ReturnData {
	float4 param1;
	float4 param2;
};`
And the retrieve code looks something like this
 *edit: modified code a tad* 
```csharp
private bool canRetrieve = false;
private AsyncTextureReader.Status retrieveStatus = AsyncTextureReader.Status.NotReady;
private AsyncTextureReader.Status requestStatus = AsyncTextureReader.Status.NotReady;

public int count = 10; //<= updates based on other variables in-game

private ComputeShader shader;
private ComputeBuffer oldBuffer;
private ComputeBuffer currentBuffer;

void StartRetrieve() {
  oldBuffer.Dispose();
  oldBuffer = currentBuffer;
  currentBufferData = new float[oldBuffer.count * 8];
  
  currentBuffer = new ComputeBuffer(count, 8 * sizeof(float), ComputeBufferType.Default);
  shader.SetBuffer(kernelID, "returnBuffer", currentBuffer);
  requestStatus = AsyncTextureReader.RequestBufferData(oldBuffer);
}

void Update(){
  shader.Dispatch(1024,1,1);

  if(requestStatus == AsyncTextureReader.Status.Succeeded) {
    if(retrieveStatus != AsyncTextureReader.Status.Succeeded) {
      retrieveStatus = AsyncTextureReader.RetrieveBufferData(oldBuffer, currentBufferData);
    } else {
      //Consume Data in other functions
      StartRetrieve(); //restart the cycle
    }
  }
}
```

ReturnBuffer gets switched with another Buffer in the 'StartRetrieve' function, so my kernel updates a new one with the latest values, while the 'older' values get retrieved.

When there's only one element in the buffer, I keep getting WrongBufferSize, even though the return float array *should* be 8 elements long for sure, this also sometimes happens when there is more then one in there, but less often for sure. 
`RetrieveBufferData failed: Error_WrongBufferSize, [info] data.Length=80, buffer.count=10, stride: 32`
running Unity 5.6.0f3 
Any idea why this is happening? I could supply you with some more source code if that's needed 
I'm extremely new to ComputeShaders, so any help is more then welcome :sweat_smile:

 *edit:* 
So it seems it's more of an issue with the computeshader.

I changed the return data to an `RWStructuredBuffer<float>`, and it stopped giving me the error. It *is* however giving me data it shouldn't get. So I guess there's a leak somewhere, and it's accessing random Data on the GPU, the function to set the data in the buffer isn't being called, yet it gets (what seems to be) pseudo-random values.
My first guess would be that I'm doing something wrong with my ConsumeBuffer, since I only have structuredBuffers everywhere else 😢

**Comment by bhnascar** [comment]
Suggestion from an interested follower of this repo: I doubt there is a leak. It seems to me that you are initiating the data copy-back _before_ even dispatching the shader that's supposed to generate the data:

```
shader.SetBuffer(kernelID, "returnBuffer", currentBuffer);
// Missing dispatch call here.
requestStatus = AsyncTextureReader.RequestBufferData(oldBuffer);
```

This would explain why you are getting pseudorandom values, because by default a `ComputeBuffer` simply contains the junk data of the GPU memory region it's mapped to. They are not automatically zeroed out like managed arrays in C#. Think C, and `malloc`, and the junk data that you would see from the heap before you overwrite it with useful values.

With regard to the buffer size issue, you are right that the total byte size of your `ComputeBuffer` matches the array you have allocated to hold the retrieved data.  However, there's a semantic inconsistency between these two lines:
```
currentBufferData = new float[oldBuffer.count * 8];  
currentBuffer = new ComputeBuffer(count, 8 * sizeof(float), ComputeBufferType.Default);
``` 
The first line is an array of 80 items, where the item is a float. The second line is an buffer of 10 items, where the item is 8 floats. It may be the case that the plugin's error checking is comparing the array count (80) to buffer count (10) and throwing an error. If so an easy fix would be to change the second line to:

```
currentBuffer = new ComputeBuffer(count * 8, sizeof(float), ComputeBufferType.Default);
```

**Comment by igniuss** [comment]
Thanks for the reply! The `currentBuffer = new ComputeBuffer(count, 8 * sizeof(float), ComputeBufferType.Default);` was actually a typo, after about 2 days of full-on debugging, and rewriting the compute shader, everything does work exactly as expected. 

I had some legacy debug code that I forgot to clean up, which caused the leak (lack of disposing buffers), and the buffer I was trying to retrieve actually did have the correct information, just shifted, *because I did some very dumb things* and forgot to take something else into account. 

the plugin works perfectly, you can close this issue @SlightlyMad 👍

**Comment by SlightlyMad** [comment]
Cool that you guys figured it out. 👍 I'm hopelessly busy.
